
erDiagram
  appointments {
    VARCHAR appointment_id PK
    VARCHAR patient_id PK
    VARCHAR doctor_id PK
    VARCHAR appointment_date
    VARCHAR appointment_time
    VARCHAR reason_for_visit
    VARCHAR status
  }
  billing {
    VARCHAR bill_id PK
    VARCHAR patient_id PK
    VARCHAR treatment_id PK
    VARCHAR bill_date
    FLOAT amount
    VARCHAR payment_method
    VARCHAR payment_status
  }
  doctors {
    VARCHAR doctor_id PK
    VARCHAR first_name
    VARCHAR last_name
    VARCHAR specialization
    INT phone_number
    INT years_experience
    VARCHAR hospital_branch
    VARCHAR email
  }
  patients {
    VARCHAR patient_id PK
    VARCHAR first_name
    VARCHAR last_name
    VARCHAR gender
    VARCHAR date_of_birth
    INT contact_number
    VARCHAR address
    VARCHAR registration_date
    VARCHAR insurance_provider
    VARCHAR insurance_number
    VARCHAR email
  }
  treatments {
    VARCHAR treatment_id PK
    VARCHAR appointment_id PK
    VARCHAR treatment_type
    VARCHAR description
    FLOAT cost
    VARCHAR treatment_date
  }
